/* EVO MKT Online — Administração (somente Gerente), upload de entrega e importação CSV. */
MODULES.administracao={label:'Administração',icon:'⚑',group:'Sistema',tone:'blue',desc:'Acessos, avisos do Portal, auditoria e backups.'};
let adminTab='acessos';
const adminApi=(p,body)=>api(p,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});
function adminOverlay(html,onClose){const o=document.createElement('div');o.className='admin-overlay';o.innerHTML=`<div class="admin-box" role="dialog" aria-modal="true">${html}</div>`;const close=()=>{o.remove();onClose&&onClose()};o.addEventListener('click',e=>{if(e.target===o||e.target.closest('[data-close]'))close()});document.body.appendChild(o);return {el:o,close}}
async function renderAdministration(){
  if(internalSession?.role!=='manager')return go('minhaarea');
  const tabs=[['acessos','Acessos'],['avisos','Avisos do Portal'],['auditoria','Auditoria'],['backups','Backups']];
  $('#content').innerHTML=`<div class="dashboard-head"><div><small>SISTEMA</small><h1>Administração</h1><p>Acessos da equipe e do Portal, avisos, auditoria e cópias de segurança.</p></div></div><div class="view-switch admin-tabs">${tabs.map(([k,l])=>`<button data-tab="${k}" class="${adminTab===k?'active':''}">${l}</button>`).join('')}</div><div id="adminBody"><div class="loading"><span></span><b>Carregando…</b></div></div>`;
  $$('.admin-tabs [data-tab]').forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;renderAdministration()});
  const body=$('#adminBody');
  try{
    if(adminTab==='acessos'){
      const u=await adminApi('/admin/users');
      body.innerHTML=`<div class="card"><div class="tablewrap"><table class="datatable"><thead><tr><th>Código</th><th>Nome</th><th>Tipo</th><th>Perfil / Segmentos</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${u.map(x=>`<tr><td><b>${esc(x.codigo)}</b></td><td>${esc(x.nome)}</td><td>${x.tipo==='portal'?'Portal':'Equipe'}</td><td>${esc(x.perfil)}</td><td>${x.ativo?'<span class="badge ok">Ativo</span>':'<span class="badge">Inativo</span>'}${x.trocarSenha?' <small>(senha temporária)</small>':''}</td><td><button class="softbtn" data-reset="${attr(x.tipo)}|${attr(x.codigo)}">Redefinir senha</button> <button class="softbtn" data-active="${attr(x.tipo)}|${attr(x.codigo)}|${x.ativo?0:1}">${x.ativo?'Desativar':'Ativar'}</button></td></tr>`).join('')}</tbody></table></div><p class="kpi-note">Ao redefinir, a senha temporária aparece uma única vez e a pessoa precisa trocá-la no próximo acesso. Sessões abertas são encerradas.</p></div>`;
      $$('[data-reset]',body).forEach(b=>b.onclick=async()=>{const [t,c]=b.dataset.reset.split('|');if(!confirm(`Gerar nova senha temporária para ${c}?`))return;try{const r=await adminApi('/admin/reset-password',{tipo:t==='portal'?'portal':'interno',codigo:c});const o=adminOverlay(`<h3>Senha temporária de ${esc(c)}</h3><p>Anote e entregue à pessoa. Ela <b>não será exibida de novo</b>.</p><div class="temp-pass">${esc(r.senhaTemporaria)}</div><div class="admin-actions"><button class="btn" data-close>Fechar</button></div>`);}catch(e){toast(e.message,'bad')}});
      $$('[data-active]',body).forEach(b=>b.onclick=async()=>{const [t,c,a]=b.dataset.active.split('|');try{await adminApi('/admin/user-active',{tipo:t==='portal'?'portal':'interno',codigo:c,ativo:a==='1'});toast('Acesso atualizado');renderAdministration()}catch(e){toast(e.message,'bad')}});
    }else if(adminTab==='avisos'){
      const n=(await adminApi('/manager/notices')).rows||[];
      body.innerHTML=`<div class="grid2"><div class="card"><h3>Novo aviso para o Portal</h3><form id="noticeForm" class="admin-form"><label>Título<input name="titulo" required maxlength="120"></label><label>Mensagem<textarea name="mensagem" rows="4" maxlength="2000"></textarea></label><label>Segmentos (separe por vírgula; vazio = todos)<input name="segmentos" placeholder="Infantil, Anos Iniciais"></label><button class="btn" type="submit">Publicar aviso</button></form></div><div class="card"><h3>Avisos publicados</h3>${n.length?n.map(x=>`<div class="notice-row"><div><b>${esc(x.titulo)}</b><small>${esc((x.segmentos||[]).join(', ')||'Todos os segmentos')} · ${fmtDateTime(x.criadoEm)}</small><p>${esc(x.mensagem)}</p></div><button class="softbtn" data-rm="${attr(x.id)}">Remover</button></div>`).join(''):'<div class="empty compact">Nenhum aviso publicado.</div>'}</div></div>`;
      $('#noticeForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());try{await adminApi('/manager/notices',f);toast('Aviso publicado');renderAdministration()}catch(er){toast(er.message,'bad')}};
      $$('[data-rm]',body).forEach(b=>b.onclick=async()=>{if(!confirm('Remover este aviso?'))return;try{await adminApi('/manager/notices/remove',{id:b.dataset.rm});renderAdministration()}catch(e){toast(e.message,'bad')}});
    }else if(adminTab==='auditoria'){
      const a=await adminApi('/admin/audit?limit=200');
      body.innerHTML=`<div class="card"><div class="tablewrap"><table class="datatable"><thead><tr><th>Quando</th><th>Quem</th><th>Ação</th><th>Módulo</th><th>Registro</th><th>IP</th></tr></thead><tbody>${a.map(x=>`<tr><td>${fmtDateTime(x.quando)}</td><td>${esc(x.ator)}</td><td>${esc(x.acao)}</td><td>${esc(x.modulo)}</td><td>${esc(x.registro)}</td><td>${esc(x.ip)}</td></tr>`).join('')||'<tr><td colspan="6">Sem eventos.</td></tr>'}</tbody></table></div><p class="kpi-note">Últimos 200 eventos (logins, criações, edições, exclusões, backups, redefinições).</p></div>`;
    }else{
      const f=await adminApi('/backup/list');
      body.innerHTML=`<div class="card"><div class="admin-actions"><button class="btn" id="bkNow">Criar backup agora</button></div><p class="kpi-note">O sistema cria um backup automático por dia e antes de exclusões permanentes (mantém os 30 mais recentes). Baixe cópias e guarde fora do servidor.</p>${f.length?`<div class="tablewrap"><table class="datatable"><thead><tr><th>Arquivo</th><th></th></tr></thead><tbody>${f.map(x=>`<tr><td>${esc(x)}</td><td><a class="softbtn" href="/api/backup/download?file=${encodeURIComponent(x)}">Baixar</a></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty compact">Nenhum backup ainda.</div>'}</div>`;
      $('#bkNow').onclick=async()=>{try{await backup();renderAdministration()}catch{}};
    }
  }catch(e){body.innerHTML=`<div class="error-state"><h2>Não foi possível carregar</h2><p>${esc(e.message)}</p></div>`}
}
function openPortalNotices(){adminTab='avisos';go('administracao')}
function openFinalDeliveryUpload(id){
  const o=adminOverlay(`<h3>Enviar arquivos da entrega</h3><p>Solicitação <b>${esc(id)}</b>. Os arquivos ficam disponíveis ao solicitante do segmento.</p><input type="file" id="delFiles" multiple><div id="delMsg" class="kpi-note"></div><div class="admin-actions"><button class="softbtn" data-close>Cancelar</button><button class="btn" id="delSend">Enviar</button></div>`);
  $('#delSend',o.el).onclick=async()=>{const files=$('#delFiles',o.el).files;if(!files.length)return toast('Escolha ao menos um arquivo','warn');const fd=new FormData();[...files].forEach(f=>fd.append('files',f));$('#delSend',o.el).disabled=true;try{const r=await fetch('/api/manager/upload?id='+encodeURIComponent(id),{method:'POST',credentials:'same-origin',headers:{'X-EVO':'1'},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha no envio');invalidate('solicitacoes');toast(`${j.files.length} arquivo(s) enviado(s)`);o.close();refreshCurrentPage&&refreshCurrentPage()}catch(e){$('#delMsg',o.el).textContent=e.message;$('#delSend',o.el).disabled=false}};
}
/* ---------- Importação CSV (Gerenciador de Anúncios / Instagram Insights) ---------- */
const CSV_MAP={
  trafego:{titulo:['nome da campanha','campanha','nome do conjunto de anuncios','periodo','titulo'],dataInicio:['inicio dos relatorios','inicio','data'],investimento:['valor usado','investimento','amount spent'],impressoes:['impressoes','impressions'],alcance:['alcance','reach'],frequencia:['frequencia','frequency'],cliques:['cliques no link','cliques todos','cliques','link clicks'],ctr:['ctr'],cpc:['cpc'],cpm:['cpm'],conversas:['conversas iniciadas','conversas','resultados'],leads:['leads','cadastros']},
  instagram:{titulo:['periodo','titulo','data'],dataInicio:['data','inicio'],seguidores:['seguidores','followers'],novosSeguidores:['novos seguidores','follows'],alcance:['alcance','reach'],impressoes:['impressoes','visualizacoes','views'],visitasPerfil:['visitas ao perfil','profile visits'],interacoes:['interacoes'],curtidas:['curtidas','likes'],comentarios:['comentarios','comments'],compartilhamentos:['compartilhamentos','shares'],salvamentos:['salvamentos','saves'],posts:['posts'],reels:['reels'],stories:['stories']}
};
const csvNorm=s=>String(s||'').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
function parseCSV(text){text=text.replace(/^﻿/,'');const first=text.split(/\r?\n/)[0]||'';const sep=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cur='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'){if(text[i+1]==='"'){cur+='"';i++}else q=false}else cur+=c}else if(c==='"')q=true;else if(c===sep){row.push(cur);cur=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cur);rows.push(row);row=[];cur=''}else cur+=c}if(cur!==''||row.length){row.push(cur);rows.push(row)}return rows.filter(r=>r.some(x=>x.trim()!==''))}
function csvToRecords(module,text){const rows=parseCSV(text);if(rows.length<2)return {records:[],unmapped:[]};const head=rows[0].map(csvNorm),map=CSV_MAP[module],pick={};Object.entries(map).forEach(([field,names])=>{for(const n of names){const i=head.indexOf(n);if(i>=0){pick[field]=i;break}}});const recs=rows.slice(1).map(r=>{const o={};Object.entries(pick).forEach(([f,i])=>{o[f]=String(r[i]??'').trim()});if(!o.titulo)o.titulo=o.dataInicio||'Importado';if(module==='trafego')o.periodo=o.periodo||String(o.dataInicio||'').slice(0,7);o.origem='IMPORTACAO_CSV';return o}).filter(o=>Object.keys(pick).some(f=>f!=='titulo'&&o[f]));return {records:recs,mapped:Object.keys(pick)}}
function importCsv(module){
  if(pref('safeMode',false))return toast('Modo Seguro ativo: importação bloqueada.','warn');
  const inp=document.createElement('input');inp.type='file';inp.accept='.csv,text/csv';
  inp.onchange=async()=>{const f=inp.files[0];if(!f)return;const text=await f.text();const {records,mapped}=csvToRecords(module,text);
    if(!records.length)return toast('Não encontrei colunas reconhecidas no CSV.','warn');
    const exist=(await getRows(module,true)).rows||[],key=r=>`${r.titulo}|${r.dataInicio||''}`,have=new Set(exist.map(key)),fresh=records.filter(r=>!have.has(key(r)));
    const o=adminOverlay(`<h3>Importar CSV — ${esc(MODULES[module].label)}</h3><p><b>${fresh.length}</b> registro(s) novo(s) de ${records.length} linha(s)${records.length-fresh.length?` (${records.length-fresh.length} já existente(s), ignorado(s))`:''}.</p><p class="kpi-note">Colunas reconhecidas: ${esc(mapped.join(', '))}. Valores em branco serão calculados ao salvar quando possível.</p><div class="tablewrap"><table class="datatable"><thead><tr>${mapped.slice(0,7).map(m=>`<th>${esc(m)}</th>`).join('')}</tr></thead><tbody>${fresh.slice(0,5).map(r=>`<tr>${mapped.slice(0,7).map(m=>`<td>${esc(r[m]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="admin-actions"><button class="softbtn" data-close>Cancelar</button><button class="btn" id="csvGo" ${fresh.length?'':'disabled'}>Importar ${fresh.length}</button></div>`);
    $('#csvGo',o.el).onclick=async()=>{$('#csvGo',o.el).disabled=true;let n=0;try{for(const r of fresh){await api(`/data?module=${module}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});n++}}catch(e){toast('Falha após '+n+' registro(s): '+e.message,'bad')}invalidate(module);o.close();toast(`${n} registro(s) importado(s)`);module==='trafego'?renderTrafficWorkspace(true):renderInstagramWorkspace(true)}};
  inp.click();
}
