/* EVO MKT Online — Administração (somente Gerente), upload de entrega e importação CSV. */
MODULES.administracao={label:'Administração',icon:'⚑',group:'Sistema',tone:'blue',desc:'Acessos, avisos do Portal, auditoria e backups.'};
let adminTab='acessos';
const adminApi=async(p,body)=>{if(!body)return api(p,{});const post=b=>api(p,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});try{return await post(body)}catch(e){if(!/Confirme sua senha/.test(e.message))throw e;const sa=prompt('Confirmação de segurança: digite sua senha de administração (Gerente).');if(!sa)throw e;return post({...body,senhaAdmin:sa})}};
function adminOverlay(html,onClose){const o=document.createElement('div');o.className='admin-overlay';o.innerHTML=`<div class="admin-box" role="dialog" aria-modal="true">${html}</div>`;const close=()=>{o.remove();onClose&&onClose()};o.addEventListener('click',e=>{if(e.target===o||e.target.closest('[data-close]'))close()});document.body.appendChild(o);return {el:o,close}}
async function renderAdministration(){
  if(internalSession?.role!=='manager')return go('minhaarea');
  const tabs=[['acessos','Acessos'],['integracoes','Integrações'],['avisos','Avisos do Portal'],['auditoria','Auditoria'],['backups','Backups']];
  $('#content').innerHTML=`<div class="dashboard-head"><div><small>SISTEMA</small><h1>Administração</h1><p>Acessos da equipe e do Portal, avisos, auditoria e cópias de segurança.</p></div></div><div class="view-switch admin-tabs">${tabs.map(([k,l])=>`<button data-tab="${k}" class="${adminTab===k?'active':''}">${l}</button>`).join('')}</div><div id="adminBody"><div class="loading"><span></span><b>Carregando…</b></div></div>`;
  $$('.admin-tabs [data-tab]').forEach(b=>b.onclick=()=>{adminTab=b.dataset.tab;renderAdministration()});
  const body=$('#adminBody');
  try{
    if(adminTab==='acessos'){
      const u=await adminApi('/admin/users');const modo=(await adminApi('/auth/mode')).modo;
      body.innerHTML=`<div class="card"><div class="tablewrap"><table class="datatable"><thead><tr><th>${modo==='codigo'?'Ficha':'Código'}</th><th>Nome</th><th>Tipo</th><th>Perfil / Segmentos</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${u.map(x=>`<tr><td><b>${esc(x.codigo)}</b></td><td>${esc(x.nome)}</td><td>${x.tipo==='portal'?'Portal':'Equipe'}</td><td>${esc(x.perfil)}</td><td>${x.ativo?'<span class="badge ok">Ativo</span>':'<span class="badge">Inativo</span>'}${x.trocarSenha&&modo!=='codigo'?' <small>(senha temporária)</small>':''}${x.pediuReset?' <span class="badge warn">pediu nova senha</span>':''}</td><td><button class="softbtn" data-reset="${attr(x.tipo)}|${attr(x.codigo)}">${modo==='codigo'?'Gerar novo código':'Redefinir senha'}</button> <button class="softbtn" data-active="${attr(x.tipo)}|${attr(x.codigo)}|${x.ativo?0:1}">${x.ativo?'Desativar':'Ativar'}</button></td></tr>`).join('')}</tbody></table></div><div class="admin-actions" style="justify-content:flex-start"><button class="softbtn" id="modeBtn">${modo==='codigo'?'Voltar ao acesso por senha':'Ativar acesso só por código'}</button> ${modo==='codigo'?'<button class="softbtn" id="viewCodes">Ver códigos de acesso</button> ':''}<button class="softbtn" id="seedEq">Criar fichas da equipe</button></div>${modo==='codigo'?'<p class="kpi-note"><b>Modo só código ligado.</b> A coluna “Ficha” é apenas o identificador interno da pessoa; o código de acesso (2 letras + 4 números) é outro e só aparece quando gerado. Para ver um novo, use “Gerar novo código”.</p>':''}<p class="kpi-note">“Criar fichas da equipe” cadastra em Equipe (com capacidade de 40h/semana) quem ainda não tem ficha; depois informe o e-mail de cada pessoa para receber avisos de atribuição e prazos. Ao redefinir, a senha temporária aparece uma única vez e a pessoa precisa trocá-la no próximo acesso. Sessões abertas são encerradas.</p></div>`;
      $('#viewCodes')&&($('#viewCodes').onclick=async()=>{const sa=prompt('Confirme sua senha de administração (Gerente):');if(!sa)return;try{const r=await adminApi('/admin/codes',{senhaAdmin:sa});adminOverlay(`<h3>Códigos de acesso</h3><p>Visível só para a Gerente. Entregue cada código individualmente; códigos em branco foram criados antes desta função — use “Gerar novo código” na pessoa.</p><div class="tablewrap"><table class="datatable"><thead><tr><th>Quem</th><th>Ficha</th><th>Código</th></tr></thead><tbody>${r.codigos.map(c=>`<tr><td>${esc(c.nome)}</td><td>${esc(c.codigo)}</td><td>${c.acesso?`<b class="temp-pass">${esc(c.acesso)}</b>`:'<small>— gerar novo —</small>'}</td></tr>`).join('')}</tbody></table></div><div class="admin-actions"><button class="btn" data-close>Fechar</button></div>`)}catch(e){toast(e.message,'bad')}});
      $('#modeBtn').onclick=async()=>{const novo=modo==='codigo'?'senha':'codigo';if(!confirm(novo==='codigo'?'Ativar acesso somente por código (2 letras + 4 números)? Serão gerados novos códigos para todos; cada pessoa precisará do código novo. Os códigos aparecem uma única vez.':'Voltar ao acesso por código + senha? Será necessário redefinir senhas para quem não tiver uma.'))return;try{const sa=prompt('Confirme sua senha de administração (Gerente):');if(!sa)return;const r=await adminApi('/admin/mode',{modo:novo,senhaAdmin:sa});if(r.codigos&&r.codigos.length){adminOverlay(`<h3>Códigos de acesso gerados</h3><p>Anote e entregue individualmente. Eles <b>não serão exibidos de novo</b>. O código antigo (ex.: ANT-3302) deixa de valer.</p><div class="tablewrap"><table class="datatable"><thead><tr><th>Quem</th><th>Código antigo</th><th>Novo código</th></tr></thead><tbody>${r.codigos.map(c=>`<tr><td>${esc(c.nome)}</td><td>${esc(c.codigo)}</td><td><b class="temp-pass">${esc(c.acesso)}</b></td></tr>`).join('')}</tbody></table></div><div class="admin-actions"><button class="btn" data-close>Fechar</button></div>`)}else toast('Modo atualizado');setTimeout(renderAdministration,300)}catch(e){toast(e.message,'bad')}};
      $('#seedEq').onclick=async()=>{try{const r=await adminApi('/admin/seed-equipe',{});toast(r.criados?`${r.criados} ficha(s) criada(s) em Equipe`:'Todas as fichas já existem');invalidate('equipe')}catch(e){toast(e.message,'bad')}};
      $$('[data-reset]',body).forEach(b=>b.onclick=async()=>{const [t,c]=b.dataset.reset.split('|');if(!confirm(`Gerar ${modo==='codigo'?'novo código de acesso':'nova senha temporária'} para ${c}?`))return;try{const r=await adminApi('/admin/reset-password',{tipo:t==='portal'?'portal':'interno',codigo:c});const o=adminOverlay(`<h3>${modo==='codigo'?'Novo código de acesso de':'Senha temporária de'} ${esc(c)}</h3><p>Anote e entregue à pessoa. Ele <b>não será exibido de novo</b>.</p><div class="temp-pass">${esc(r.senhaTemporaria)}</div><div class="admin-actions"><button class="btn" data-close>Fechar</button></div>`);}catch(e){toast(e.message,'bad')}});
      $$('[data-active]',body).forEach(b=>b.onclick=async()=>{const [t,c,a]=b.dataset.active.split('|');try{await adminApi('/admin/user-active',{tipo:t==='portal'?'portal':'interno',codigo:c,ativo:a==='1'});toast('Acesso atualizado');renderAdministration()}catch(e){toast(e.message,'bad')}});
    }else if(adminTab==='integracoes'){
      const [st,queue,log]=await Promise.all([adminApi('/integrations/status'),adminApi('/integrations/instagram/queue'),adminApi('/integrations/log')]);const ig=st.instagram,gg=st.google;
      const badge=(on,txt)=>`<span class="badge ${on?'ok':''}">${on?txt:'Não conectado'}</span>`;
      const uriRow=(l,u)=>`<div class="uri-row"><small>${l}</small><code>${esc(u)}</code><button class="softbtn copy-uri" data-u="${attr(u)}">Copiar</button></div>`;
      body.innerHTML=`<div class="int-note">As conexões usam as <b>contas do Colégio</b>. Siga o passo a passo em <b>GUIA_INTEGRACOES.md</b> (vem no pacote) para criar o app na Meta e o projeto no Google. Os segredos ficam criptografados no servidor e nunca voltam para a tela.</div>
      <div class="grid2"><section class="card int-card"><div class="card-title"><div><small>META</small><h3>Instagram</h3></div>${badge(ig.conectado,'@'+esc(ig.usuario||'conectado'))}</div>
        <form id="metaForm" class="admin-form"><label>App ID da Meta<input name="meta_app_id" value="${attr(ig.appId||'')}" autocomplete="off"></label><label>App Secret<input name="meta_app_secret" type="password" placeholder="${ig.configurado?'•••••••• (já salvo — deixe vazio para manter)':'cole o App Secret'}" autocomplete="off"></label><div class="admin-actions" style="justify-content:flex-start"><button class="softbtn" type="submit">Salvar credenciais</button>${ig.configurado?`<a class="btn" href="/api/integrations/meta/connect">${ig.conectado?'Reconectar':'Conectar com Facebook/Instagram'}</a>`:''}</div></form>
        ${uriRow('URI de redirecionamento OAuth válida (cadastre na Meta):',st.redirectUris.meta)}
        ${ig.conectado?`<p class="kpi-note">Página: ${esc(ig.pagina||'—')} · token válido até ${ig.expiraEm?fmtDate(ig.expiraEm):'—'} (renovado automaticamente) · última sincronização: ${ig.ultimaSync?fmtDateTime(ig.ultimaSync):'nunca'}</p><div class="admin-actions" style="justify-content:flex-start"><button class="btn" id="igSync">Sincronizar métricas agora</button><button class="softbtn" id="igDisc">Desconectar</button></div>`:`<div class="admin-actions" style="justify-content:flex-start"><button class="softbtn" id="igManual">Colar token manualmente</button></div>`}
      </section>
      <section class="card int-card"><div class="card-title"><div><small>GOOGLE</small><h3>Agenda · Drive · Planilhas</h3></div>${badge(gg.conectado,esc(gg.email||'conectado'))}</div>
        <form id="gForm" class="admin-form"><label>Client ID<input name="g_client_id" value="${attr(gg.clientId||'')}" autocomplete="off"></label><label>Client Secret<input name="g_client_secret" type="password" placeholder="${gg.configurado?'•••••••• (já salvo — deixe vazio para manter)':'cole o Client Secret'}" autocomplete="off"></label><div class="admin-actions" style="justify-content:flex-start"><button class="softbtn" type="submit">Salvar credenciais</button>${gg.configurado?`<a class="btn" href="/api/integrations/google/connect">${gg.conectado?'Reconectar':'Conectar com Google'}</a>`:''}</div></form>
        ${uriRow('URI de redirecionamento autorizado (cadastre no Google Cloud):',st.redirectUris.google)}
        ${gg.conectado?`<div class="int-actions"><button class="softbtn" id="gCal">Sincronizar Agenda</button><button class="softbtn" id="gSheet">Exportar para Planilhas</button><button class="softbtn" id="gDrive">Enviar entregas ao Drive</button><button class="softbtn" id="gDisc">Desconectar</button></div>
        <label class="check-row"><input type="checkbox" id="gAuto" ${gg.driveAuto?'checked':''}> Enviar ao Drive automaticamente cada entrega anexada em Solicitações</label>
        <p class="kpi-note">Agenda: ${gg.ultimaAgenda?fmtDateTime(gg.ultimaAgenda):'nunca sincronizada'} · Planilha: ${gg.planilhaUrl?`<a href="${attr(gg.planilhaUrl)}" target="_blank" rel="noopener">abrir</a> (${gg.ultimaPlanilha?fmtDateTime(gg.ultimaPlanilha):'—'})`:'ainda não criada'} ${gg.driveFolder?'· pasta do Drive criada':''}</p>`:''}
      </section></div>
      <section class="card"><div class="card-title"><div><small>INSTAGRAM</small><h3>Fila de publicação</h3></div></div><p class="kpi-note">Marque “Publicar no Instagram automaticamente = SIM” no conteúdo, anexe a mídia (JPEG ou vídeo MP4/MOV) e deixe o status APROVADO ou PROGRAMADO com a data de publicação: o sistema publica no horário (cron de 10 em 10 min). Carrossel ainda é manual.</p>
        ${queue.length?`<div class="tablewrap"><table class="datatable"><thead><tr><th>Conteúdo</th><th>Formato</th><th>Publicação</th><th>Mídia</th><th>Estado</th><th>Ações</th></tr></thead><tbody>${queue.map(c=>`<tr><td><b>${esc(c.titulo)}</b><br><small>${esc(c.id)} · ${esc(c.status)}</small></td><td>${esc(c.formato||'—')}</td><td>${c.publicacaoEm?fmtDateTime(c.publicacaoEm):'—'}</td><td>${c.midia?'✓ anexada':'—'}</td><td>${c.publicado?`<span class="badge ok">Publicado</span> <a href="${attr(c.link)}" target="_blank" rel="noopener">ver</a>`:c.estado==='ERRO'?`<span class="badge warn" title="${attr(c.erro)}">Erro</span><br><small>${esc(c.erro)}</small>`:c.estado==='PROCESSANDO'?'<span class="badge warn">Processando</span>':'<span class="badge">Na fila</span>'}</td><td>${c.publicado?'':`<button class="softbtn ig-media" data-id="${attr(c.id)}">${c.midia?'Trocar mídia':'Anexar mídia'}</button> <button class="btn ig-pub" data-id="${attr(c.id)}" ${c.midia&&ig.conectado?'':'disabled'}>Publicar agora</button>`}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty compact">Nenhum conteúdo marcado para publicar no Instagram.</div>'}</section>
      <section class="card"><div class="card-title"><div><small>HISTÓRICO</small><h3>Últimas operações</h3></div></div>${log.length?`<div class="tablewrap"><table class="datatable"><tbody>${log.map(l=>`<tr><td>${fmtDateTime(l.quando)}</td><td>${esc(l.servico)}</td><td>${l.nivel==='erro'?'<span class="badge warn">erro</span>':'ok'}</td><td>${esc(l.msg)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty compact">Sem operações registradas.</div>'}</section>
      <div class="card"><h3>Agendamento automático (Cron Jobs na Hostinger)</h3><p class="kpi-note">Publicar no horário: <code>${esc(st.cron)} publicar</code> — a cada 10 minutos.<br>Sincronizar tudo (métricas, Agenda, Planilhas, Drive): <code>${esc(st.cron)} sincronizar</code> — 1 vez por dia.</p></div>`;
      const save=async(formId)=>{const f=Object.fromEntries(new FormData($(formId)).entries());try{await adminApi('/integrations/settings',f);toast('Credenciais salvas');renderAdministration()}catch(e){toast(e.message,'bad')}};
      $('#metaForm').onsubmit=e=>{e.preventDefault();save('#metaForm')};$('#gForm').onsubmit=e=>{e.preventDefault();save('#gForm')};
      $$('.copy-uri',body).forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(b.dataset.u);toast('Endereço copiado')});
      const run=(sel,path,msg)=>{const el=$(sel);if(el)el.onclick=async()=>{el.disabled=true;toast('Processando…');try{const r=await adminApi(path,{});toast(typeof msg==='function'?msg(r):msg);renderAdministration()}catch(e){toast(e.message,'bad');el.disabled=false;renderAdministration()}}};
      run('#igSync','/integrations/instagram/sync',r=>`${r.periodos} período(s) atualizados na tela Instagram`);
      run('#gCal','/integrations/google/calendar/sync',r=>`Agenda: ${r.para_google} enviados, ${r.do_google} alterados pelo Google, ${r.criados} novos, ${r.removidos} removidos`);
      run('#gSheet','/integrations/google/sheets/export',r=>`Planilha atualizada (${Object.keys(r.abas).length} abas)`);
      run('#gDrive','/integrations/google/drive/send-entregas',r=>`${r.arquivos} arquivo(s) enviados ao Drive`);
      const disc=(sel,path)=>{const el=$(sel);if(el)el.onclick=async()=>{if(!confirm('Desconectar? As credenciais salvas continuam; apenas o acesso é removido.'))return;await adminApi(path,{});renderAdministration()}};disc('#igDisc','/integrations/meta/disconnect');disc('#gDisc','/integrations/google/disconnect');
      $('#igManual')&&($('#igManual').onclick=async()=>{const tok=prompt('Cole o token de acesso (de usuário do sistema ou de longa duração):');if(!tok)return;const id=prompt('ID da conta Instagram profissional (deixe vazio para descobrir automaticamente):')||'';try{await adminApi('/integrations/meta/token',{token:tok,ig_user_id:id});toast('Token salvo');renderAdministration()}catch(e){toast(e.message,'bad')}});
      $('#gAuto')&&($('#gAuto').onchange=async e=>{await adminApi('/integrations/settings',{g_auto_drive_entregas:e.target.checked});toast(e.target.checked?'Envio automático ao Drive ligado':'Envio automático desligado')});
      $$('.ig-media',body).forEach(b=>b.onclick=()=>{const inp=document.createElement('input');inp.type='file';inp.accept='.jpg,.jpeg,.mp4,.mov,image/jpeg,video/mp4,video/quicktime';inp.onchange=async()=>{const fd=new FormData();fd.append('files',inp.files[0]);try{const r=await fetch('/api/integrations/instagram/media?id='+encodeURIComponent(b.dataset.id),{method:'POST',credentials:'same-origin',headers:{'X-EVO':'1'},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);invalidate('conteudos');toast('Mídia anexada');renderAdministration()}catch(e){toast(e.message,'bad')}};inp.click()});
      $$('.ig-pub',body).forEach(b=>b.onclick=async()=>{if(!confirm('Publicar agora no Instagram? Esta ação não pode ser desfeita pelo sistema.'))return;b.disabled=true;toast('Publicando… pode levar até 1 minuto');try{const r=await adminApi('/integrations/instagram/publish',{id:b.dataset.id});invalidate('conteudos');toast(r.status==='PUBLICADO'?'Publicado no Instagram!':'Instagram está processando o vídeo; o sistema conclui sozinho');renderAdministration()}catch(e){toast(e.message,'bad');renderAdministration()}});
    }else if(adminTab==='avisos'){
      const n=(await adminApi('/manager/notices')).rows||[];
      body.innerHTML=`<div class="grid2"><div class="card"><h3>Novo aviso para o Portal</h3><form id="noticeForm" class="admin-form"><label>Título<input name="titulo" required maxlength="120"></label><label>Mensagem<textarea name="mensagem" rows="4" maxlength="2000"></textarea></label><label>Segmentos (separe por vírgula; vazio = todos)<input name="segmentos" placeholder="Infantil, Anos Iniciais"></label><button class="btn" type="submit">Publicar aviso</button></form></div><div class="card"><h3>Avisos publicados</h3>${n.length?n.map(x=>`<div class="notice-row"><div><b>${esc(x.titulo)}</b><small>${esc((x.segmentos||[]).join(', ')||'Todos os segmentos')} · ${fmtDateTime(x.criadoEm)}</small><p>${esc(x.mensagem)}</p></div><button class="softbtn" data-rm="${attr(x.id)}">Remover</button></div>`).join(''):'<div class="empty compact">Nenhum aviso publicado.</div>'}</div></div>`;
      $('#noticeForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());try{await adminApi('/manager/notices',f);toast('Aviso publicado');renderAdministration()}catch(er){toast(er.message,'bad')}};
      $$('[data-rm]',body).forEach(b=>b.onclick=async()=>{if(!confirm('Remover este aviso?'))return;try{await adminApi('/manager/notices/remove',{id:b.dataset.rm});renderAdministration()}catch(e){toast(e.message,'bad')}});
    }else if(adminTab==='auditoria'){
      const a=await adminApi('/admin/audit?limit=200');
      body.innerHTML=`<div class="card"><div class="tablewrap"><table class="datatable"><thead><tr><th>Quando</th><th>Quem</th><th>Ação</th><th>Módulo</th><th>Registro</th><th>IP</th></tr></thead><tbody>${a.map(x=>`<tr><td>${fmtDateTime(x.quando)}</td><td>${esc(x.ator)}</td><td>${esc(x.acao)}</td><td>${esc(x.modulo)}</td><td>${esc(x.registro)}</td><td>${esc(x.ip)}</td></tr>`).join('')||'<tr><td colspan="6">Sem eventos.</td></tr>'}</tbody></table></div><p class="kpi-note">Últimos 200 eventos (logins, criações, edições, exclusões, backups, redefinições).</p></div>`;
    }else{
      const f=await adminApi('/backup/list');
      body.innerHTML=`<div class="card"><div class="admin-actions"><button class="btn" id="bkNow">Criar backup agora</button></div><p class="kpi-note">O sistema cria um backup automático por dia e antes de exclusões permanentes (mantém os 30 mais recentes). Baixe cópias e guarde fora do servidor.</p>${f.length?`<div class="tablewrap"><table class="datatable"><thead><tr><th>Arquivo</th><th></th></tr></thead><tbody>${f.map(x=>`<tr><td>${esc(x)}</td><td><a class="softbtn" href="/api/backup/download?file=${encodeURIComponent(x)}">Baixar</a></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty compact">Nenhum backup ainda.</div>'}</div>`;
      $('#bkNow').onclick=async()=>{try{await backup();renderAdministration()}catch{}};
    }
  }catch(e){body.innerHTML=`<div class="error-state"><h2>Não foi possível carregar</h2><p>${esc(e.message)}</p></div>`}
}
function openPortalNotices(){adminTab='avisos';go('administracao')}
function openFinalDeliveryUpload(id){
  const o=adminOverlay(`<h3>Enviar arquivos da entrega</h3><p>Solicitação <b>${esc(id)}</b>. Os arquivos ficam disponíveis ao solicitante do segmento.</p><input type="file" id="delFiles" multiple><div id="delMsg" class="kpi-note"></div><div class="admin-actions"><button class="softbtn" data-close>Cancelar</button><button class="btn" id="delSend">Enviar</button></div>`);
  $('#delSend',o.el).onclick=async()=>{const files=$('#delFiles',o.el).files;if(!files.length)return toast('Escolha ao menos um arquivo','warn');const fd=new FormData();[...files].forEach(f=>fd.append('files',f));$('#delSend',o.el).disabled=true;try{const r=await fetch('/api/manager/upload?id='+encodeURIComponent(id),{method:'POST',credentials:'same-origin',headers:{'X-EVO':'1'},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha no envio');invalidate('solicitacoes');toast(`${j.files.length} arquivo(s) enviado(s)`);o.close();refreshCurrentPage&&refreshCurrentPage()}catch(e){$('#delMsg',o.el).textContent=e.message;$('#delSend',o.el).disabled=false}};
}
/* ---------- Importação CSV (Gerenciador de Anúncios / Instagram Insights) ---------- */
const CSV_MAP={
  trafego:{titulo:['nome da campanha','campanha','nome do conjunto de anuncios','periodo','titulo'],dataInicio:['inicio dos relatorios','inicio','data'],investimento:['valor usado','investimento','amount spent'],impressoes:['impressoes','impressions'],alcance:['alcance','reach'],frequencia:['frequencia','frequency'],cliques:['cliques no link','cliques todos','cliques','link clicks'],ctr:['ctr'],cpc:['cpc'],cpm:['cpm'],conversas:['conversas iniciadas','conversas','resultados'],leads:['leads','cadastros']},
  instagram:{titulo:['periodo','titulo','data'],dataInicio:['data','inicio'],seguidores:['seguidores','followers'],novosSeguidores:['novos seguidores','follows'],alcance:['alcance','reach'],impressoes:['impressoes','visualizacoes','views'],visitasPerfil:['visitas ao perfil','profile visits'],interacoes:['interacoes'],curtidas:['curtidas','likes'],comentarios:['comentarios','comments'],compartilhamentos:['compartilhamentos','shares'],salvamentos:['salvamentos','saves'],posts:['posts'],reels:['reels'],stories:['stories']}
};
const csvNorm=s=>String(s||'').normalize('NFD').replace(/[̀-ͯ]/g,'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
function parseCSV(text){text=text.replace(/^﻿/,'');const first=text.split(/\r?\n/)[0]||'';const sep=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cur='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'){if(text[i+1]==='"'){cur+='"';i++}else q=false}else cur+=c}else if(c==='"')q=true;else if(c===sep){row.push(cur);cur=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cur);rows.push(row);row=[];cur=''}else cur+=c}if(cur!==''||row.length){row.push(cur);rows.push(row)}return rows.filter(r=>r.some(x=>x.trim()!==''))}
function csvToRecords(module,text){const rows=parseCSV(text);if(rows.length<2)return {records:[],unmapped:[]};const head=rows[0].map(csvNorm),map=CSV_MAP[module],pick={};Object.entries(map).forEach(([field,names])=>{for(const n of names){const i=head.indexOf(n);if(i>=0){pick[field]=i;break}}});const recs=rows.slice(1).map(r=>{const o={};Object.entries(pick).forEach(([f,i])=>{o[f]=String(r[i]??'').trim()});if(!o.titulo)o.titulo=o.dataInicio||'Importado';if(module==='trafego')o.periodo=o.periodo||String(o.dataInicio||'').slice(0,7);o.origem='IMPORTACAO_CSV';return o}).filter(o=>Object.keys(pick).some(f=>f!=='titulo'&&o[f]));return {records:recs,mapped:Object.keys(pick)}}
function importCsv(module){
  if(pref('safeMode',false))return toast('Modo Seguro ativo: importação bloqueada.','warn');
  const inp=document.createElement('input');inp.type='file';inp.accept='.csv,text/csv';
  inp.onchange=async()=>{const f=inp.files[0];if(!f)return;const text=await f.text();const {records,mapped}=csvToRecords(module,text);
    if(!records.length)return toast('Não encontrei colunas reconhecidas no CSV.','warn');
    const exist=(await getRows(module,true)).rows||[],key=r=>`${r.titulo}|${r.dataInicio||''}`,have=new Set(exist.map(key)),fresh=records.filter(r=>!have.has(key(r)));
    const o=adminOverlay(`<h3>Importar CSV — ${esc(MODULES[module].label)}</h3><p><b>${fresh.length}</b> registro(s) novo(s) de ${records.length} linha(s)${records.length-fresh.length?` (${records.length-fresh.length} já existente(s), ignorado(s))`:''}.</p><p class="kpi-note">Colunas reconhecidas: ${esc(mapped.join(', '))}. Valores em branco serão calculados ao salvar quando possível.</p><div class="tablewrap"><table class="datatable"><thead><tr>${mapped.slice(0,7).map(m=>`<th>${esc(m)}</th>`).join('')}</tr></thead><tbody>${fresh.slice(0,5).map(r=>`<tr>${mapped.slice(0,7).map(m=>`<td>${esc(r[m]||'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="admin-actions"><button class="softbtn" data-close>Cancelar</button><button class="btn" id="csvGo" ${fresh.length?'':'disabled'}>Importar ${fresh.length}</button></div>`);
    $('#csvGo',o.el).onclick=async()=>{$('#csvGo',o.el).disabled=true;let n=0;try{for(const r of fresh){await api(`/data?module=${module}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)});n++}}catch(e){toast('Falha após '+n+' registro(s): '+e.message,'bad')}invalidate(module);o.close();toast(`${n} registro(s) importado(s)`);module==='trafego'?renderTrafficWorkspace(true):renderInstagramWorkspace(true)}};
  inp.click();
}
/* Botão "Instalar app" (PWA) quando o navegador oferece */
window.addEventListener('evo-can-install',()=>{if(document.getElementById('installBtn'))return;const t=document.querySelector('.topactions');if(!t)return;const b=document.createElement('button');b.id='installBtn';b.className='btn secondary';b.textContent='Instalar app';b.onclick=async()=>{if(await evoInstallApp())b.remove()};t.insertBefore(b,t.firstChild)});

/* retorno do login OAuth (Meta/Google): abre a aba Integrações e mostra o resultado */
(()=>{const q=new URLSearchParams(location.search),r=q.get('int');if(!r)return;adminTab='integracoes';window.addEventListener('load',()=>setTimeout(()=>{const ok=/_ok$/.test(r);toast(ok?(r.startsWith('meta')?'Instagram conectado!':'Google conectado!'):'Não foi possível conectar: '+(q.get('msg')||'erro'),ok?'ok':'bad');history.replaceState(null,'','?page=administracao')},900))})();
