const fs=require('fs');const out=fs.readFileSync(process.argv[2],'utf8');
const pw=k=>out.match(new RegExp(k+'[^:]*: (\\S+)'))[1];
const B=(process.env.BASE||'http://127.0.0.1:8080')+'/api';let ok=0,bad=0;
const t=(n,c)=>{c?ok++:bad++;console.log(c?'OK  ':'FAIL',n)};
async function call(p,{m='GET',b,ck,pt,csrf=true}={}){const h={};if(b)h['Content-Type']='application/json';if(ck)h.Cookie=ck;if(pt)h['X-Portal-Token']=pt;if(csrf&&!pt)h['X-EVO']='1';const r=await fetch(B+p,{method:m,headers:h,body:b?JSON.stringify(b):undefined});let j;try{j=await r.json()}catch{}return{s:r.status,j,c:r.headers.get('set-cookie')}}
(async()=>{
 let r=await call('/auth/login',{m:'POST',b:{codigo:'NAT-3301',senha:'errada'}});t('login senha errada=401',r.s===401);
 r=await call('/data?module=tarefas');t('sem sessão=401',r.s===401);
 r=await call('/auth/login',{m:'POST',b:{codigo:'NAT-3301',senha:pw('NAT-3301')}});t('login gerente',r.s===200&&r.j.mustChange===true);
 const G=r.c.split(';')[0];
 r=await call('/auth/password',{m:'POST',ck:G,b:{atual:pw('NAT-3301'),nova:'fraca'}});t('senha fraca recusada',r.s===400);
 r=await call('/auth/password',{m:'POST',ck:G,b:{atual:pw('NAT-3301'),nova:'SenhaForte2026x'}});t('troca senha',r.s===200);
 r=await call('/data?module=tarefas',{ck:G});t('lista importada (acentos ok)',r.s===200&&r.j.rows.length===1&&r.j.rows[0].id==='TAR-0007'&&r.j.rows[0].descricao.includes('ç'));
 r=await call('/data?module=tarefas',{m:'POST',ck:G,b:{titulo:'Nova',status:'NOVO',custom:'x'}});t('cria TAR-0008 (continua contador)',r.s===201&&r.j.id==='TAR-0008');
 r=await call('/data?module=tarefas',{m:'POST',ck:G,b:{titulo:'CSRF'},csrf:false});t('POST sem X-EVO bloqueado',r.s===403);
 r=await call('/data?module=tarefas&id=TAR-0008',{m:'PUT',ck:G,b:{status:'EM ANDAMENTO',id:'HACK'}});t('edita e ignora id',r.s===200&&r.j.id==='TAR-0008'&&r.j.status==='EM ANDAMENTO');
 r=await call('/data?module=tarefas&id=TAR-0008',{m:'DELETE',ck:G});t('exclui→lixeira',r.s===200);
 r=await call('/data?module=lixeira',{ck:G});const lx=r.j.rows[0];t('item na lixeira com origem',lx&&lx.origem==='tarefas'&&lx.idOriginal==='TAR-0008');
 r=await call('/data?module=tarefas',{m:'POST',ck:G,b:{titulo:'Outra'}});t('ID excluído NÃO reutilizado (TAR-0009)',r.j.id==='TAR-0009');
 r=await call('/data?module=tarefas',{ck:G});t('headers dinâmicos incluem custom',r.j.headers.includes('custom'));
 r=await call('/search?q=importada',{ck:G});t('busca',r.s===200&&r.j.length===1&&r.j[0].module==='tarefas');
 r=await call('/backup',{m:'POST',ck:G});t('backup',r.s===200&&/evo_backup/.test(r.j.file));
 r=await call('/health',{ck:G});t('health',r.s===200&&r.j.modules.length===19);
 r=await call('/auth/login',{m:'POST',b:{codigo:'ANT-3302',senha:pw('ANT-3302')}});const E=r.c.split(';')[0];
 r=await call('/data?module=equipe',{m:'POST',ck:E,b:{titulo:'x'}});t('equipe não grava em Equipe',r.s===403);
 r=await call('/backup',{m:'POST',ck:E});t('equipe não faz backup',r.s===403);
 r=await call('/data?module=lixeira&id='+lx.id,{m:'DELETE',ck:E});t('equipe não exclui permanente',r.s===403);
 r=await call('/data?module=tarefas',{m:'POST',ck:E,b:{titulo:'Da equipe'}});t('equipe cria tarefa',r.s===201);
 r=await call('/portal/login',{m:'POST',b:{codigo:'INF-2601',senha:'xxxx'}});t('portal senha errada=401',r.s===401);
 r=await call('/portal/login',{m:'POST',b:{codigo:'INF-2601',senha:pw('INF-2601')}});t('portal login',r.s===200&&r.j.token);const P=r.j.token;
 r=await call('/portal/requests',{m:'POST',pt:P,b:{titulo:'Stories matrícula',objetivo:'Divulgar',segmento:'Infantil',prioridade:'NORMAL'}});t('portal cria demanda',r.s===201&&r.j.id==='SOL-0001'&&r.j.status==='AGUARDANDO TRIAGEM');const sid=r.j.id;
 r=await call('/portal/requests',{m:'POST',pt:P,b:{titulo:'x',objetivo:'y',segmento:'Ensino Médio'}});t('portal bloqueia outro segmento',r.s===403);
 r=await call('/portal/requests',{m:'POST',pt:P,b:{titulo:'x',objetivo:'y',segmento:'Infantil',prioridade:'URGENTE'}});t('urgente exige motivo',r.s===400);
 r=await call('/portal/login',{m:'POST',b:{codigo:'MED-2604',senha:pw('MED-2604')}});const M=r.j.token;
 r=await call('/portal/requests',{pt:M});t('isolamento: Médio não vê demanda do Infantil',r.s===200&&r.j.rows.length===0);
 r=await call('/data?module=solicitacoes&id='+sid,{m:'PUT',pt:M,b:{respostaSolicitante:'oi'}});t('Médio não edita demanda alheia',r.s===403);
 r=await call('/data?module=tarefas',{pt:P});t('portal não lê tarefas',r.s===401||r.s===403);
 r=await call('/data?module=solicitacoes&id='+sid,{m:'PUT',pt:P,b:{aprovacaoSolicitante:'APROVADO'}});t('aprovar sem estar aguardando=409',r.s===409);
 r=await call('/portal/users',{pt:P});t('portal não lista usuários',r.s===401);
 r=await call('/health',{pt:P});t('portal sem /health',r.s===401);
 const fd=new FormData();fd.append('files',new Blob(['%PDF-1.4 teste']),'brief.pdf');
 let rr=await fetch(B+'/portal/upload?id='+sid,{method:'POST',headers:{'X-Portal-Token':P},body:fd});let jj=await rr.json();t('upload pdf',rr.status===200&&jj.files[0].startsWith('ANEXOS/SOLICITACOES/SOL-0001/'));
 const fd2=new FormData();fd2.append('files',new Blob(['<?php echo 1;']),'x.php');rr=await fetch(B+'/portal/upload?id='+sid,{method:'POST',headers:{'X-Portal-Token':P},body:fd2});t('upload .php recusado',rr.status===400);
 rr=await fetch(B+'/portal/file?path='+encodeURIComponent(jj.files[0]),{headers:{'X-Portal-Token':P}});t('download próprio',rr.status===200);
 rr=await fetch(B+'/portal/file?path='+encodeURIComponent(jj.files[0]),{headers:{'X-Portal-Token':M}});t('download de outro segmento=403',rr.status===403);
 rr=await fetch(B+'/portal/file?path='+encodeURIComponent('ANEXOS/SOLICITACOES/../../config.php'),{headers:{'X-Portal-Token':P}});t('path traversal bloqueado',rr.status===400);
 let last;for(let i=0;i<6;i++)last=await call('/auth/login',{m:'POST',b:{codigo:'MON-3303',senha:'errada'+i}});t('rate limit 429',last.s===429);
 r=await call('/admin/reset-password',{m:'POST',ck:G,b:{tipo:'portal',codigo:'INF-2601'}});t('reset senha portal',r.s===200&&r.j.senhaTemporaria.length===12);const r2pass=r.j.senhaTemporaria;
 r=await call('/portal/requests',{pt:P});t('sessão do portal revogada após reset',r.s===401);

 // ---- v4.1.0 ----
 r=await call('/admin/users',{ck:G});t('gerente lista acessos',r.s===200&&r.j.length===10&&!JSON.stringify(r.j).includes('hash'));
 r=await call('/admin/users',{ck:E});t('equipe não lista acessos',r.s===403);
 r=await call('/admin/audit',{ck:G});t('auditoria registra eventos',r.s===200&&r.j.length>5&&r.j.some(x=>x.acao==='login'));
 r=await call('/data?module=tarefas',{m:'POST',ck:G,b:{titulo:'Da gerente',responsavel:'Monique Vilante'}});const alheio=r.j.id;
 r=await call('/data?module=tarefas&id='+alheio,{m:'DELETE',ck:E});t('equipe não exclui item de outra pessoa',r.s===403);
 r=await call('/data?module=tarefas',{m:'POST',ck:E,b:{titulo:'Minha'}});const meu=r.j.id;t('criadoPor carimbado',!!meu);
 r=await call('/data?module=tarefas&id='+meu,{m:'DELETE',ck:E});t('equipe exclui o que criou',r.s===200);
 r=await call('/manager/notices',{m:'POST',ck:G,b:{titulo:'Recesso',mensagem:'Sem expediente sexta',segmentos:'Infantil'}});t('gerente publica aviso',r.s===200);const nid=r.j.id;
 const P2=(await call('/portal/login',{m:'POST',b:{codigo:'INF-2601',senha:r2pass}})).j.token;
 r=await call('/portal/notices',{pt:P2});t('Infantil vê aviso',r.j.rows.some(n=>n.id===nid));
 const M2=(await call('/portal/login',{m:'POST',b:{codigo:'MED-2604',senha:pw('MED-2604')}})).j.token;
 r=await call('/portal/notices',{pt:M2});t('Médio NÃO vê aviso do Infantil',!r.j.rows.some(n=>n.id===nid));
 r=await call('/manager/notices/remove',{m:'POST',ck:G,b:{id:nid}});t('remove aviso',r.s===200);
 const fd3=new FormData();fd3.append('files',new Blob(['%PDF-1.4 entrega']),'final.pdf');
 let r3=await fetch(B+'/manager/upload?id=SOL-0001',{method:'POST',headers:{Cookie:G,'X-EVO':'1'},body:fd3});const j3=await r3.json();t('gerente envia entrega',r3.status===200&&j3.files[0].includes('/ENTREGA/'));
 r3=await fetch(B+'/portal/file?path='+encodeURIComponent(j3.files[0]),{headers:{'X-Portal-Token':P2}});t('solicitante baixa a entrega',r3.status===200);
 r=await call('/admin/user-active',{m:'POST',ck:G,b:{tipo:'portal',codigo:'MED-2604',ativo:false}});t('desativa acesso do Médio',r.s===200);
 r=await call('/portal/requests',{pt:M2});t('sessão do Médio encerrada',r.s===401);
 r=await call('/portal/login',{m:'POST',b:{codigo:'MED-2604',senha:pw('MED-2604')}});t('Médio desativado não entra',r.s===401);
 r=await call('/admin/user-active',{m:'POST',ck:G,b:{tipo:'interno',codigo:'NAT-3301',ativo:false}});t('gerente não se desativa',r.s===400);

 // ---- v4.2.0 ----
 r=await call('/data?module=equipe',{ck:G});t('instalador criou as 5 fichas de Equipe',r.j.rows.length===5);
 await call('/data?module=equipe&id='+r.j.rows.find(x=>x.titulo==='Maria Eduarda').id,{m:'DELETE',ck:G});
 r=await call('/admin/seed-equipe',{m:'POST',ck:G,b:{}});t('seed recria só a ficha que falta (1)',r.s===200&&r.j.criados===1);
 r=await call('/admin/seed-equipe',{m:'POST',ck:G,b:{}});t('seed é idempotente (0)',r.j.criados===0);
 r=await call('/data?module=equipe',{ck:G});const eqAnt=r.j.rows.find(x=>x.titulo==='Antônio Filho');t('ficha com capacidade 40',eqAnt&&eqAnt.capacidadeSemanal==='40');
 await call('/data?module=equipe&id='+eqAnt.id,{m:'PUT',ck:G,b:{email:'antonio@teste.com'}});
 const MAILLOG=process.env.MAILLOG;
 r=await call('/data?module=tarefas',{m:'POST',ck:G,b:{titulo:'Atribuída ao Antônio',responsavel:'Antônio Filho',prazo:'2020-01-01'}});const tid=r.j.id;
 if(MAILLOG){const ml=require('fs').readFileSync(MAILLOG,'utf8');t('e-mail de atribuição enviado ao Antônio',ml.includes('antonio@teste.com')&&ml.includes('Nova atribuição'));}
 const E2=(await call('/auth/login',{m:'POST',b:{codigo:'EDU-3305',senha:pw('EDU-3305')}})).c.split(';')[0];
 r=await call('/data?module=tarefas&id='+tid,{m:'PUT',ck:E2,b:{responsavel:'Monique Vilante'}});t('Equipe não reatribui item de outra pessoa',r.s===403);
 r=await call('/data?module=tarefas&id='+tid,{m:'PUT',ck:E2,b:{status:'EM ANDAMENTO'}});t('Equipe ainda edita outros campos (colaboração)',r.s===200);
 r=await call('/data?module=tarefas&id='+tid,{m:'PUT',ck:G,b:{responsavel:'Monique Vilante'}});t('Gerente reatribui',r.s===200);
 r=await call('/auth/forgot',{m:'POST',b:{codigo:'ALU-3304',tipo:'interno'},csrf:false});t('esqueci senha: resposta genérica',r.s===200&&r.j.ok);
 r=await call('/auth/forgot',{m:'POST',b:{codigo:'NAO-EXISTE',tipo:'interno'},csrf:false});t('esqueci senha: não revela se existe',r.s===200&&r.j.mensagem.includes('Se o código existir'));
 r=await call('/admin/users',{ck:G});t('Acessos marca quem pediu nova senha',r.j.find(x=>x.codigo==='ALU-3304').pediuReset===true&&!r.j.find(x=>x.codigo==='EDU-3305').pediuReset);
 await call('/admin/reset-password',{m:'POST',ck:G,b:{tipo:'interno',codigo:'ALU-3304'}});
 r=await call('/admin/users',{ck:G});t('após redefinir, marcação some',r.j.find(x=>x.codigo==='ALU-3304').pediuReset===false);
 r=await call('/portal/requests',{m:'POST',pt:(await call('/portal/login',{m:'POST',b:{codigo:'FIN-2603',senha:pw('FIN-2603')}})).j.token,b:{titulo:'Teste e-mail',objetivo:'x',segmento:'Anos Finais',prioridade:'NORMAL'}});
 if(MAILLOG){const ml=require('fs').readFileSync(MAILLOG,'utf8');t('e-mail à Gerente de nova demanda do Portal',ml.includes('Nova demanda: Teste e-mail'));}
 await call('/data?module=tarefas',{m:'POST',ck:G,b:{titulo:'Prazo vencido do Antônio',responsavel:'Antônio Filho',prazo:'2020-01-02'}});
 console.log(`\n${ok} ok, ${bad} falhas`);process.exit(bad?1:0)})();
